
;; Compiled from #P"/home/frank/quicklisp/local-projects/climbe/schema/CIM2.42.0/CIM_EthernetPortStatistics.xml"

(in-package #:climbe)


(DEFCIM-CLASS CIM_ETHERNETPORTSTATISTICS (CIM_NETWORKPORTSTATISTICS)
              ((PACKETSTRANSMITTED UINT64 :CIM-NAME "PacketsTransmitted"
                :QUALIFIERS
                ((:OVERRIDE "PacketsTransmitted")
                 (:DESCRIPTION
                  "The total number of packets that are transmitted.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIF.DMTF|Network Adapter 802 Port|001.6")))
                :INITFORM NIL)
               (PACKETSRECEIVED UINT64 :CIM-NAME "PacketsReceived" :QUALIFIERS
                ((:OVERRIDE "PacketsReceived")
                 (:DESCRIPTION
                  "The total number of packets that are received.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIF.DMTF|Network Adapter 802 Port|001.8")))
                :INITFORM NIL)
               (SYMBOLERRORS UINT32 :CIM-NAME "SymbolErrors" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of times that there was an invalid data symbol when a valid carrier was present. The count can be incremented only once per carrier event, even if multiple symbol errors occur during the carrier event.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsSymbolErrors")))
                :INITFORM NIL)
               (ALIGNMENTERRORS UINT32 :CIM-NAME "AlignmentErrors" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames that are received on a particular interface that are not an integral number of octets in length and do not pass the FCS check. The count represented by an instance of this object is incremented when the alignment error status is returned by the MAC layer to the LLC (or other MAC user). Received frames for which multiple error conditions obtained are, according to the conventions of IEEE 802.3 Layer Management, counted exclusively according to the error status presented to the LLC.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsAlignmentErrors")))
                :INITFORM NIL)
               (FCSERRORS UINT32 :CIM-NAME "FCSErrors" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames that are received on a particular interface that are an integral number of octets in length, but do not pass the FCS check. The count represented by an instance of this object is incremented when the frame check error status is returned by the MAC layer to the LLC (or other MAC user). Received frames for which multiple error conditions obtained are, according to the conventions of the error status presented to the LLC.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsFCSErrors")))
                :INITFORM NIL)
               (SINGLECOLLISIONFRAMES UINT32 :CIM-NAME "SingleCollisionFrames"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The number of successfully transmitted frames on a particular interface for which transmission is inhibited by exactly one collision. A frame that is counted by an instance of this object is not counted by the corresponding instance of the MultipleCollisionFrames property.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsSingleCollisionFrames")))
                :INITFORM NIL)
               (MULTIPLECOLLISIONFRAMES UINT32 :CIM-NAME
                "MultipleCollisionFrames" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of successfully transmitted frames on a particular interface for which transmission is inhibited by more than one collision. A frame that is counted by an instance of this object is not counted by the corresponding instance of the SingleCollisionFrames property.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsMultipleCollisionFrames")))
                :INITFORM NIL)
               (SQETESTERRORS UINT32 :CIM-NAME "SQETestErrors" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of times that the SQE TEST ERROR message is generated by the PLS sublayer for a particular interface. The SQE TEST ERROR message is defined in section 7.2.2.2.4 of ANSI/IEEE 802.3-1985 and its generation is described in section 7.2.4.6 of the same document.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsSQETestErrors")))
                :INITFORM NIL)
               (DEFERREDTRANSMISSIONS UINT32 :CIM-NAME "DeferredTransmissions"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames for which the first transmission attempt on a particular interface is delayed because the medium is busy. The count represented by an instance of this object does not include frames involved in collisions.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsDeferredTransmissions")))
                :INITFORM NIL)
               (LATECOLLISIONS UINT32 :CIM-NAME "LateCollisions" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of times that a collision is detected on a particular interface later than 512 bit-times into the transmission of a packet. Five hundred and twelve bit- times corresponds to 51.2 microseconds on a 10 Mbit/s system. A (late) collision included in a count represented by an instance of this object is also considered as a (generic) collision for purposes of other collision-related statistics.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsLateCollisions")))
                :INITFORM NIL)
               (EXCESSIVECOLLISIONS UINT32 :CIM-NAME "ExcessiveCollisions"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames for which transmission on a particular interface fails due to excessive collisions.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsExcessiveCollisions")))
                :INITFORM NIL)
               (INTERNALMACTRANSMITERRORS UINT32 :CIM-NAME
                "InternalMACTransmitErrors" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames for which transmission on a particular interface fails due to an internal MAC sublayer transmit error. A frame is counted by an instance of this object only if it is not counted by the corresponding instance of either the LateCollisions property, the Excessive Collisions property, or the CarrierSenseErrors property. The precise meaning of the count that is represented by an instance of this object is implementation-specific. In particular, an instance of this object can represent a count of transmission errors on a particular interface that are not otherwise counted.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsInternalMacTransmitErrors")))
                :INITFORM NIL)
               (INTERNALMACRECEIVEERRORS UINT32 :CIM-NAME
                "InternalMACReceiveErrors" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames for which reception on a particular interface fails due to an internal MAC sublayer receive error. A frame is counted by an instance of this object only if it is not counted by the corresponding instance of either the FrameTooLongs property, the AlignmentErrors property, or the FCSErrors property. The precise meaning of the count that is represented by an instance of this object is implementation-specific. For example, an instance of this object can represent a count of receive errors on a particular interface that are not otherwise counted.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsInternalMacReceiveErrors")))
                :INITFORM NIL)
               (CARRIERSENSEERRORS UINT32 :CIM-NAME "CarrierSenseErrors"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The number of times that the carrier sense condition was lost or never asserted when attempting to transmit a frame on a particular interface. The count represented by an instance of this object can be incremented only once per transmission attempt, even if the carrier sense condition fluctuates during a transmission attempt.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsCarrierSenseErrors")))
                :INITFORM NIL)
               (FRAMETOOLONGS UINT32 :CIM-NAME "FrameTooLongs" :QUALIFIERS
                ((:DESCRIPTION
                  "The number of frames received on a particular interface that exceed the maximum permitted frame size. The count represented by an instance of this object is incremented when the FrameTooLong status is returned by the MAC layer to the LLC (or other MAC user). Received frames for which multiple error conditions obtained are, according to the conventions of IEEE 802.3 Layer Management, counted exclusively according to the error status presented to the LLC.")
                 :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|EtherLike-MIB.dot3StatsFrameTooLongs")))
                :INITFORM NIL)
               (BYTESTRANSMITTED UINT64 :CIM-NAME "BytesTransmitted"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The total number of bytes that are transmitted, including framing characters.")
                 (NIL "Bytes") :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|MIB-II.ifOutOctets"
                   "MIF.DMTF|Network Adapter 802 Port|001.7"))
                 (:P-UNIT "byte"))
                :INITFORM NIL)
               (BYTESRECEIVED UINT64 :CIM-NAME "BytesReceived" :QUALIFIERS
                ((:DESCRIPTION
                  "The total number of bytes that are received, including framing characters.")
                 (NIL "Bytes") :COUNTER
                 (:MAPPING-STRINGS
                  ("MIB.IETF|MIB-II.ifInOctets"
                   "MIF.DMTF|Network Adapter 802 Port|001.9"))
                 (:P-UNIT "byte"))
                :INITFORM NIL)
               (INSTANCEID STRING :CIM-NAME "InstanceID" :QUALIFIERS
                (:KEY (:OVERRIDE "InstanceID")
                 (:DESCRIPTION
                  "Within the scope of the instantiating Namespace, InstanceID opaquely and uniquely identifies an instance of this class. In order to ensure uniqueness within the NameSpace, the value of InstanceID SHOULD be constructed using the following 'preferred' algorithm: 
<OrgID>:<LocalID> 
Where <OrgID> and <LocalID> are separated by a colon ':', and where <OrgID> MUST include a copyrighted, trademarked or otherwise unique name that is owned by the business entity creating/defining the InstanceID, or is a registered ID that is assigned to the business entity by a recognized global authority (This is similar to the <Schema Name>_<Class Name> structure of Schema class names.) In addition, to ensure uniqueness <OrgID> MUST NOT contain a colon (':'). When using this algorithm, the first colon to appear in InstanceID MUST appear between <OrgID> and <LocalID>. 
<LocalID> is chosen by the business entity and SHOULD not be re-used to identify different underlying (real-world) elements. If the above 'preferred' algorithm is not used, the defining entity MUST assure that the resultant InstanceID is not re-used across any InstanceIDs produced by this or other providers for this instance's NameSpace. 
For DMTF defined instances, the 'preferred' algorithm MUST be used with the <OrgID> set to 'CIM'."))
                :INITFORM NIL)
               (ELEMENTNAME STRING :CIM-NAME "ElementName" :QUALIFIERS
                (:REQUIRED (:OVERRIDE "ElementName")
                 (:DESCRIPTION
                  "The user friendly name for this instance of StatisticalData. In addition, the user friendly name can be used as a index property for a search of query. (Note: Name does not have to be unique within a namespace.)"))
                :INITFORM NIL)
               (STARTSTATISTICTIME DATETIME :CIM-NAME "StartStatisticTime"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The time, relative to managed element where the statistic was collected, when the first measurement was taken. If the statistic is reset, the StartStatisticTime is the time when the reset was performed."))
                :INITFORM NIL)
               (STATISTICTIME DATETIME :CIM-NAME "StatisticTime" :QUALIFIERS
                ((:DESCRIPTION
                  "The time the most recent measurement was taken, relative to the managed element where the statistic was collected."))
                :INITFORM NIL)
               (SAMPLEINTERVAL DATETIME :CIM-NAME "SampleInterval" :QUALIFIERS
                ((:DESCRIPTION
                  "Some statistics are sampled at consistent time intervals. This property provides the sample interval so that client applications can determine the minimum time that new statistics should be pulled. If the statistics are not sampled at consistent time intervals, this property must be set to a zero time interval."))
                :INITFORM "00000000000000.000000:000")
               (CAPTION STRING :CIM-NAME "Caption" :QUALIFIERS
                ((:DESCRIPTION
                  "The Caption property is a short textual description (one- line string) of the object.")
                 (:MAX-LEN "64"))
                :INITFORM NIL)
               (DESCRIPTION STRING :CIM-NAME "Description" :QUALIFIERS
                ((:DESCRIPTION
                  "The Description property provides a textual description of the object."))
                :INITFORM NIL))
              (:CIM-NAME "CIM_EthernetPortStatistics")
              (:QUALIFIERS (:VERSION "2.10.0")
               (:UML-PACKAGE-PATH "CIM::Device::Ports")
               (:DESCRIPTION
                "The EthernetPortStatistics class describes the statistics for the EthernetPort.")))
(DEFCIM-METHOD RESETSELECTEDSTATS
    ((INSTANCE CIM_ETHERNETPORTSTATISTICS)
     (SELECTEDSTATISTICS (ARRAY STRING) "SelectedStatistics" :IN
      (:DESCRIPTION "Array of strings indicating which statistics to reset.")))
    ((:CIM-NAME "ResetSelectedStats")
     (:QUALIFIERS
      (:DESCRIPTION
       "Method to reset one or more of the instance's statistics. The method takes one parameter as input - an array of strings indicating which statistics to reset. If all the statistics in the instance should be reset, the first element of the array MUST be set to \"All\" or \"ALL\". If one or more individual statistics should be reset, the corresponding property names are entered into the elements of the array. 
The method returns 0 if successful, 1 if not supported, and any other value if an error occurred. A method is specified so that the StatisticalInformation's provider/ instrumentation, which calculates the statistics, can reset its internal processing, counters, etc. 
In a subclass, the set of possible return codes could be specified, using a ValueMap qualifier on the method. The strings to which the ValueMap contents are 'translated' may also be specified in the subclass as a Values array qualifier."))))