
;; Compiled from #P"/home/frank/quicklisp/local-projects/climbe/schema/CIM2.42.0/CIM_J2eeNotification.xml"

(in-package #:climbe)


(DEFCIM-CLASS CIM_J2EENOTIFICATION (CIM_PROCESSINDICATION)
              ((INDICATIONIDENTIFIER STRING :CIM-NAME "IndicationIdentifier"
                :QUALIFIERS
                ((:OVERRIDE "IndicationIdentifier")
                 (:DESCRIPTION
                  "The identifier for the indication, represented as the name of the source J2EE managed object that generated the event. The name MUST be constructed using the form specified in JSR77.3.1.1.1.")
                 (:MAPPING-STRINGS ("JSR77.JCP|JSR77.4.2.1.1 source|V1.0"))
                 (:MODEL-CORRESPONDENCE ("CIM_J2eeManagedObject.InstanceID")))
                :INITFORM NIL)
               (SEQUENCENUMBER SINT64 :CIM-NAME "SequenceNumber" :QUALIFIERS
                ((:OVERRIDE "SequenceNumber")
                 (:DESCRIPTION
                  "The sequence number of the indication. Identifies the position of the indication in a stream of indications. The sequence number provides a means of determining the order of sequential indications that occurred with the same timestamp (within the minimum supported unit of time).")
                 (:MAPPING-STRINGS ("JSR77.JCP|JSR77.4.2.1.3 sequence|V1.0"))
                 (:MODEL-CORRESPONDENCE ("CIM_Indication.SequenceContext")))
                :INITFORM NIL)
               (INDICATIONTYPE UINT16 :CIM-NAME "IndicationType" :QUALIFIERS
                ((:DESCRIPTION
                  "The type of the indication. The type is assigned by the source object that generated the indication. It conveys the semantic meaning of the particular indication. The standard types (starting, stopping, running, etc.) MUST be described by this property's enumeration. Other values MAY also be specified by entering 1 (\"Other\") in this property and placing the type's string value in OtherIndicationType. The latter SHOULD be interpreted as a number of dot-separated components. This allows some structure in the naming of indication types. Source objects are free to define any types that they wish to use when naming the indications that they generate. 

Note that this enumeration is defined by examining J2eeManagedObject's OperationalStatus property, by the creation or deletion of the J2eeManagedObject instance, or is the decision of the JSR77 experts or the implementation. It is not a one-to-one mapping of the OperationalStatus property in ManagedSystemElement, and is therefore a unique enumeration and specific ProcessIndication.")
                 (:VALUE-MAP ("0" "1" "2" "3" "4" "5" "6" "7" "8"))
                 (:VALUES
                  ("Unknown" "Other" "j2ee.object.created"
                   "j2ee.object.deleted" "j2ee.state.starting"
                   "j2ee.state.running" "j2ee.state.stopping"
                   "j2ee.state.stopped" "j2ee.state.failed"))
                 (:MAPPING-STRINGS ("JSR77.JCP|JSR77.4.2.1.4 type|V1.0"))
                 (:MODEL-CORRESPONDENCE
                  ("CIM_J2eeNotification.OtherIndicationType")))
                :INITFORM NIL)
               (OTHERINDICATIONTYPE STRING :CIM-NAME "OtherIndicationType"
                :QUALIFIERS
                ((:DESCRIPTION
                  "The type of the indication when a non-standard event is generated by the source object. This value MUST be specified when IndicationType is set to 1 (\"Other\").")
                 (:MODEL-CORRESPONDENCE
                  ("CIM_J2eeNotification.IndicationType")))
                :INITFORM NIL)
               (MESSAGE STRING :CIM-NAME "Message" :QUALIFIERS
                ((:DESCRIPTION
                  "An informational message about the indication."))
                :INITFORM NIL)
               (USERDATA STRING :CIM-NAME "UserData" :QUALIFIERS
                ((:DESCRIPTION
                  "Optional data that the notication broadcaster wishes to communicate to listeners. The content of the data is user specific. The UserData property may be null.")
                 :OCTET-STRING)
                :INITFORM NIL)
               (INDICATIONTIME DATETIME :CIM-NAME "IndicationTime" :QUALIFIERS
                ((:DESCRIPTION
                  "The time and date of creation of the Indication. The property may be set to NULL if the entity creating the Indication is not capable of determining this information. Note that IndicationTime may be the same for two Indications that are generated in rapid succession."))
                :INITFORM NIL)
               (PERCEIVEDSEVERITY UINT16 :CIM-NAME "PerceivedSeverity"
                :QUALIFIERS
                ((:DESCRIPTION
                  "An enumerated value that describes the severity of the Indication from the notifier's point of view: 
1 - Other, by CIM convention, is used to indicate that the Severity's value can be found in the OtherSeverity property. 
3 - Degraded/Warning should be used when its appropriate to let the user decide if action is needed. 
4 - Minor should be used to indicate action is needed, but the situation is not serious at this time. 
5 - Major should be used to indicate action is needed NOW. 
6 - Critical should be used to indicate action is needed NOW and the scope is broad (perhaps an imminent outage to a critical resource will result). 
7 - Fatal/NonRecoverable should be used to indicate an error occurred, but it's too late to take remedial action. 
2 and 0 - Information and Unknown (respectively) follow common usage. Literally, the Indication is purely informational or its severity is simply unknown.")
                 (:VALUE-MAP ("0" "1" "2" "3" "4" "5" "6" "7" ".."))
                 (:VALUES
                  ("Unknown" "Other" "Information" "Degraded/Warning" "Minor"
                   "Major" "Critical" "Fatal/NonRecoverable" "DMTF Reserved"))
                 (:MAPPING-STRINGS
                  ("Recommendation.ITU|X733.Perceived severity")))
                :INITFORM NIL)
               (OTHERSEVERITY STRING :CIM-NAME "OtherSeverity" :QUALIFIERS
                ((:DESCRIPTION
                  "Holds the value of the user defined severity value when 'PerceivedSeverity' is 1 (\"Other\").")
                 (:MODEL-CORRESPONDENCE
                  ("CIM_AlertIndication.PerceivedSeverity")))
                :INITFORM NIL)
               (INDICATIONFILTERNAME STRING :CIM-NAME "IndicationFilterName"
                :QUALIFIERS
                ((:DESCRIPTION
                  "An identifier for the indication filter that selects this indication and causes it to be sent. This property is to be filled out by the indication sending service. The value shall be correlatable with the Name property of the instance of CIM_IndicationFilter describing the criteria of the indication. The value of the IndicationFilterName should be formatted using the following algorithm: < OrgID > : < LocalID >, where < OrgID > and < LocalID > are separated by a colon (:) and < OrgID > shall include a copyrighted, trademarked, or otherwise unique name that is owned by the business entity that is creating or defining the value or that is a registered ID assigned to the business entity by a recognized global authority. In addition, to ensure uniqueness, < OrgID > shall not contain a colon (:).When using this algorithm, the first colon to appear in the value shall appear between < OrgID > and < LocalID >. < LocalID > is chosen by the business entity and shall be used uniquely.")
                 (:MODEL-CORRESPONDENCE ("CIM_IndicationFilter.Name")))
                :INITFORM NIL)
               (SEQUENCECONTEXT STRING :CIM-NAME "SequenceContext" :QUALIFIERS
                ((:DESCRIPTION
                  "The sequence context portion of a sequence identifier for the indication. The sequence number portion of the sequence identifier is provided by the SequenceNumber property. The combination of both property values represents the sequence identifier for the indication.
The sequence identifier for the indication enables a CIM listener to identify duplicate indications when the CIM service attempts the delivery retry of indications, to reorder indications that arrive out-of-order, and to detect lost indications.
If a CIM service does not support sequence identifiers for indications, this property shall be NULL.
If a CIM service supports sequence identifiers for indications, this property shall be maintained by the CIM service for each registered listener destination, and its value shall uniquely identify the CIM service and the indication service within the CIM service such that restarts of the CIM service and deregistration of listener destinations to the CIM service cause the value to change, without reusing earlier values for a sufficiently long time.
When retrying the delivery of an indication, this property shall have the same value as in the original delivery.
To guarantee this uniqueness, the property value should be constructed using the following format (defined in ABNF): sequence-context = indication-service-name \"#\" cim-service-start-id \"#\" listener-destination-creation-time
Where: indication-service-name is the value of the Name property of the CIM_IndicationService instance responsible for delivering the indication. cim-service-start-id is an identifier that uniquely identifies the CIM service start, for example via a timestamp of the start time, or via a counter that increases for each start or restart. listener-destination-creation-time is a timestamp of the creation time of the CIM_ListenerDestination instance representing the listener destination.
Since this format is only a recommendation, CIM clients shall treat the value as an opaque identifier for the sequence context and shall not rely on this format.")
                 (:MODEL-CORRESPONDENCE ("CIM_Indication.SequenceNumber")))
                :INITFORM NIL)
               (CORRELATEDINDICATIONS (ARRAY STRING) :CIM-NAME
                "CorrelatedIndications" :QUALIFIERS
                ((:DESCRIPTION
                  "A list of IndicationIdentifiers whose notifications are correlated with (related to) this one.")
                 (:MAPPING-STRINGS
                  ("Recommendation.ITU|X733.Correlated notifications"))
                 (:MODEL-CORRESPONDENCE
                  ("CIM_Indication.IndicationIdentifier")))
                :INITFORM NIL))
              (:CIM-NAME "CIM_J2eeNotification")
              (:QUALIFIERS :INDICATION (:VERSION "2.8.0")
               (:UML-PACKAGE-PATH "CIM::Application::J2eeAppServer")
               (:DESCRIPTION
                "The J2eeNotification class specifies the properties that must be included in every event that is generated by a J2EE managed object that supports the event model. All management systems that support event notification must support all of the properties in this class.")))